name: "publish"

on:
  push:
    tags:
      - "*"

jobs:

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/jsonschema-gen/
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Test
        run: |
          pip install -U pip setuptools wheel
          pip install -e .[test]
          pytest
      - name: Build
        run: |
          pip install build twine
          python -m build --wheel --outdir dist/
          twine check dist/*.whl
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: jsonschema-gen
          path: dist/*.whl
