name: "3.11"

on:
  push:
    branches: [ master ]
    paths: [ 'src', 'tests' ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Python install
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -e .[test]

    - name: Tests
      run: |
        pytest
